language: go

go:
  - 1.11
  - 1.x
  - master

env:
  - GO111MODULE=on

matrix:
  fast_finish: true
  allow_failures:
    - go: master

install:
  - go get -u golang.org/x/lint/golint

script:
  - cat ./adjectives.txt | perl ./isAlphabetized.pl
  - cat ./nouns.txt | perl ./isAlphabetized.pl
  - go test ./...
  - golint ./...
